# Generated by Django 4.2.6 on 2024-05-17 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='tub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='base.tub'),
        ),
    ]
