# Generated by Django 5.0.6 on 2024-05-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_rating_tub'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='desciption',
            field=models.TextField(null=True),
        ),
    ]
