# Generated by Django 5.0.6 on 2024-05-20 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rating_desciption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(max_length=15)),
                ('active', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
                ('is_multi_use', models.BooleanField(default=False)),
                ('tub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tube_discount', to='base.tub')),
            ],
        ),
    ]
