# Generated by Django 5.0.6 on 2024-05-20 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='value',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
