# Generated by Django 5.0.6 on 2024-05-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_discount_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='price_per_day_after_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
