# Generated by Django 5.0.6 on 2024-05-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_price_per_day_after_discount_reservation_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('answer', models.CharField(blank=True, max_length=511, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tub',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tub_logos/'),
        ),
    ]
