# Generated by Django 5.0.6 on 2024-05-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_faq_tub_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tub',
            name='image',
        ),
        migrations.AddField(
            model_name='tub',
            name='logo_img',
            field=models.ImageField(null=True, upload_to='logo_tub/'),
        ),
    ]
