# Generated by Django 5.0.6 on 2024-06-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='counted_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
