# Generated by Django 5.0.6 on 2024-07-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_faq_date_faq_is_published_faq_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tub',
            name='price_per_week',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
